// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	mux "github.com/gorilla/mux"
	mock "github.com/stretchr/testify/mock"
)

// AuthCallbackHandlerInterface is an autogenerated mock type for the AuthCallbackHandlerInterface type
type AuthCallbackHandlerInterface struct {
	mock.Mock
}

// ServeLogin provides a mock function with given fields: r
func (_m *AuthCallbackHandlerInterface) ServeLogin(r *mux.Router) {
	_m.Called(r)
}

// NewAuthCallbackHandlerInterface creates a new instance of AuthCallbackHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthCallbackHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthCallbackHandlerInterface {
	mock := &AuthCallbackHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
