// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	mux "github.com/gorilla/mux"
	mock "github.com/stretchr/testify/mock"
)

// HomeHandlerInterface is an autogenerated mock type for the HomeHandlerInterface type
type HomeHandlerInterface struct {
	mock.Mock
}

// ServeHome provides a mock function with given fields: r
func (_m *HomeHandlerInterface) ServeHome(r *mux.Router) {
	_m.Called(r)
}

// NewHomeHandlerInterface creates a new instance of HomeHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHomeHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HomeHandlerInterface {
	mock := &HomeHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
