// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	mux "github.com/gorilla/mux"
	mock "github.com/stretchr/testify/mock"
)

// LogoutHandlerInterface is an autogenerated mock type for the LogoutHandlerInterface type
type LogoutHandlerInterface struct {
	mock.Mock
}

// ServeLogout provides a mock function with given fields: r
func (_m *LogoutHandlerInterface) ServeLogout(r *mux.Router) {
	_m.Called(r)
}

// NewLogoutHandlerInterface creates a new instance of LogoutHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogoutHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogoutHandlerInterface {
	mock := &LogoutHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
