// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	mux "github.com/gorilla/mux"
	mock "github.com/stretchr/testify/mock"
)

// ProtectedHandlerInterface is an autogenerated mock type for the ProtectedHandlerInterface type
type ProtectedHandlerInterface struct {
	mock.Mock
}

// ServeProtected provides a mock function with given fields: r
func (_m *ProtectedHandlerInterface) ServeProtected(r *mux.Router) {
	_m.Called(r)
}

// NewProtectedHandlerInterface creates a new instance of ProtectedHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProtectedHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProtectedHandlerInterface {
	mock := &ProtectedHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
