// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	sessions "github.com/gorilla/sessions"
	mock "github.com/stretchr/testify/mock"
)

// SessionCookieStore is an autogenerated mock type for the SessionCookieStore type
type SessionCookieStore struct {
	mock.Mock
}

// GetCookie provides a mock function with given fields: r
func (_m *SessionCookieStore) GetCookie(r *http.Request) (*sessions.Session, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetCookie")
	}

	var r0 *sessions.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*sessions.Session, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *sessions.Session); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessions.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSessionCookieStore creates a new instance of SessionCookieStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionCookieStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionCookieStore {
	mock := &SessionCookieStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
