services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: swift-menu-db
    ports:
      - "3399:3306"
    volumes:
      - mysqltest:/var/lib/mysql


volumes:
  mysqltest: