services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: swift-menu-db
    ports:
      - "3390:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data: